name: release_manager

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      pr_number:
        required: true
        type: string

jobs:
  processing_release_manager:
    name: collecting_release_version
    runs-on: [ self-hosted, linux, code_release ]
    steps:
    - id: step1
      name: Checking which files changed 
      run: |
      
        echo "Get the changes before we merge"
        org_repo=${{ inputs.repo_name }}
        release_repo_name=$(echo ${org_repo} | cut -d/ -f2)
        actual_repo_name=$(echo ${org_repo} | sed 's/_release//')
        
        echo "Repo name is ${{ inputs.repo_name }} and the PR number is ${{ inputs.pr_number }}"
        URL="https://api.github.com/repos/${{ inputs.repo_name }}/commits/REF"
        
        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL)
        echo $URL
        echo $FILES
        exit 0
        FILES=$(curl -s -X GET -H "Authorization: Bearer $(cat ~/.gh_secrets)" -G $URL | jq -r '.[] | .filename')
               
        if [[ $FILES == 'release.txt' ]]
        then
          echo "Release.txt modified, procedding further to deploy the code on puppet master..."
          echo "file_name=$FILES" >> $GITHUB_OUTPUT
          echo "Repo_Name=$actual_repo_name" >> $GITHUB_OUTPUT
          echo "PR_number=${{ inputs.pr_number }}" >> $GITHUB_OUTPUT
          
          cd ~/git
          if [[ -d ${release_repo_name} ]] ;  then rm -rf ${release_repo_name} ; fi
          
          gh auth login --with-token < ~/.gh_secrets
          
          echo "Cloing the repo"
          gh repo clone "https://github.com/${org_repo}"
          
          cd ${release_repo_name}
          echo "I am in ${release_repo_name}"
          
          echo "Checking out the PR"
          gh pr checkout ${{ inputs.pr_number }}
          changes=$(git diff main | grep ^+ | grep -v release.txt | sed 's/+//g')
          
          echo "+++++++++++++++++++++++++++++++++++++++++++++"
          git diff main
          echo "+++++++++++++++++++++++++++++++++++++++++++++"
          
          echo ${changes}
          #echo "::set-output name=changes_to_deploy::$(echo ${changes})"
          echo "changes_to_deploy=$(echo $changes | tr ' ' '\n' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          echo ${changes_to_deploy}
          
        else 
          echo ""
          echo -e "\033[31;1;4mThis workflow designed to merge, changes in release.txt, found $FILES files with changes exiting....\033[0m"
          
          #echo "::set-output name=file_name::$(echo ${FILES})"
          echo "file_name=$FILES" >> $GITHUB_OUTPUT
          echo ""
        fi
    - id: step2
      name: PR Approval and Merging
      if: ${{ success() && steps.step1.outputs.file_name == 'release.txt' }} 
      run: |
        #Setting UP Variables#
        orgAndRepo=${{ inputs.repo_name }}
        orgName=$(echo $orgAndRepo | cut -d'/' -f1)
        repoName=$(echo $orgAndRepo | cut -d'/' -f2)
        
        echo "Printing Vars...."
        echo "Org Name - $orgName"
        echo "Repo Name - $repoName"
        
        #Execution Starts from here#
        cd ~/git
        if [ -d ${repoName} ]; then rm -rf ${repoName}; fi
        gh auth login --with-token < ~/.gh_secrets
        echo ""
        echo "Checking the status of GH login...."
        gh auth status
        echo ""
        
        echo "Clonning the repository...."
        gh repo clone "https://github.com/${orgAndRepo}"
        echo ""
        cd $repoName
        echo "I am in $repoName"
        echo ""
        echo "Checking out the PR...."
        gh pr checkout ${{ inputs.pr_number }}
        echo ""
        
        echo "Merging PR...."
        gh pr merge --merge
        if [ $? -ne 0 ]; then
          echo ""
          echo "PR Merger Failed!!"
          gh auth logout --hostname github.com
          echo ""
          exit 1
        else
          echo ""
          echo "PR Has Been Merged Successfully!!"
          gh auth logout --hostname github.com
        fi
#    - id: step3
#      name: Call actions
#      if: ${{ success() && steps.step1.outputs.file_name == 'release.txt' }}
#      uses: pcherukusfdc/release_manager@main
#      with:
#        repo_name: '${{ github.repository }}'
#        pr_num: '${{ github.event.pull_request.number }}'
#        pr_changes: '${{ steps.step1.outputs.changes_to_deploy }}'
    outputs:
      file_name: ${{ steps.step1.outputs.file_name }}
      changes_from_pr: ${{ steps.step1.outputs.changes_to_deploy }}
      REPO_name: ${{ steps.step1.outputs.REPO_name }}
      PR_Number: ${{ steps.step1.outputs.PR_number }}
      
  processing_release_manager2:
    needs: processing_release_manager
    if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
    runs-on: [ self-hosted, linux, code_release ]
    strategy:
      matrix:
        list_of_changes: ${{ fromJSON(needs.processing_release_manager.outputs.changes_from_pr) }}
    steps:
    - id: step3
      name: call actions
      if: ${{ success() && needs.processing_release_manager.outputs.file_name == 'release.txt' }}
      uses: pcherukusfdc/release_manager@main
      with:
        repo_name: '${{ needs.processing_release_manager.outputs.REPO_name }}'
        pr_num: '${{ needs.processing_release_manager.outputs.PR_Number }}'
        #pr_changes: ${{ needs.processing_release_manager.outputs.changes_from_pr }}
        pr_changes: ${{ matrix.list_of_changes }}
